/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bridge-straight-pillar.glb -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    ['bridge-straight-pillar_1']: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
}

export function Bridge(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/public/castle/GLB_format/bridge-straight-pillar.glb'
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['bridge-straight-pillar_1'].geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/public/castle/GLB_format/bridge-straight-pillar.glb')
