/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../../public/castle/GLB_format/bridge-draw.glb -t -k 
*/

import * as THREE from "three";
import { type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["bridge-draw_1"]: THREE.Mesh;
  };
  materials: {
    colormap: THREE.MeshStandardMaterial;
  };
};

export function BrideDraw(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/public/castle/GLB_format/bridge-draw.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="bridge-draw_1"
        geometry={nodes["bridge-draw_1"].geometry}
        material={materials.colormap}
      />
    </group>
  );
}

useGLTF.preload("/public/castle/GLB_format/bridge-draw.glb");
