/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../../public/pirate/GLBformat/cannon.glb -t -k 
*/

import * as THREE from "three";
import { type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
type GLTFResult = GLTF & {
  nodes: {
    cannon_1: THREE.Mesh;
    Group: THREE.Mesh;
    Group_1: THREE.Mesh;
  };
  materials: {
    colormap: THREE.MeshStandardMaterial;
  };
};

export function Cannon(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/public/pirate/GLBformat/cannon.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="cannon_1"
        geometry={nodes.cannon_1.geometry}
        material={materials.colormap}
      >
        <mesh
          name="Group"
          geometry={nodes.Group.geometry}
          material={materials.colormap}
          position={[-0.229, 0.3, -0.825]}
          rotation={[0, 0, 0.262]}
        />
        <mesh
          name="Group_1"
          geometry={nodes.Group_1.geometry}
          material={materials.colormap}
          position={[0.519, 0.222, -0.825]}
          rotation={[0, 0, -0.262]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/public/pirate/GLBformat/cannon.glb");
