/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 GLB_format/flag-banner-long.glb -t -k 
*/

import * as THREE from 'three'
import { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['flag-banner-long_1']: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
}

export function FlagBannerLong(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/public/castle/GLB_format/flag-banner-long.glb'
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="flag-banner-long_1"
        geometry={nodes['flag-banner-long_1'].geometry}
        material={materials.colormap}
      />
    </group>
  )
}

useGLTF.preload('/public/castle/GLB_format/flag-banner-long.glb')
