/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../../public/pirate/GLBformat/grass-plant.glb -t -k 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['grass-plant_1']: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
}

export function GrassPlant(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    'public/pirate/GLBformat/grass-plant.glb'
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="grass-plant_1"
        geometry={nodes['grass-plant_1'].geometry}
        material={materials.colormap}
      />
    </group>
  )
}

useGLTF.preload('/grass-plant.glb')
