/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../../public/castle/GLB_format/ground.glb -t -k 
*/

import * as THREE from 'three'
import { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ground_1: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
}

export function Ground(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/public/castle/GLB_format/ground.glb'
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="ground_1" geometry={nodes.ground_1.geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/public/castle/GLB_format/ground.glb')
