/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../../public/castle/GLB_format/rocks-large.glb -t -k 
*/

import * as THREE from "three";
import { type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import meshUrl from "/castle/GLB_format/rocks-large.glb";

type GLTFResult = GLTF & {
  nodes: {
    ["rocks-large_1"]: THREE.Mesh;
  };
  materials: {
    colormap: THREE.MeshStandardMaterial;
  };
};

export function RocksLarge(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(meshUrl) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="rocks-large_1"
        geometry={nodes["rocks-large_1"].geometry}
        material={materials.colormap}
      />
    </group>
  );
}

useGLTF.preload(meshUrl);
