/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../../public/castle/GLB_format/siege-trebuchet.glb -t -k 
*/

import * as THREE from "three";
import { type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["siege-trebuchet_1"]: THREE.Mesh;
    arm: THREE.Mesh;
    catapult_2: THREE.Mesh;
    weight_2: THREE.Mesh;
    catapult: THREE.Mesh;
    weight: THREE.Mesh;
    wheel: THREE.Mesh;
    wheel_1: THREE.Mesh;
    wheel_2: THREE.Mesh;
    wheel_3: THREE.Mesh;
  };
  materials: {
    colormap: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/public/castle/GLB_format/siege-trebuchet.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="siege-trebuchet_1"
        geometry={nodes["siege-trebuchet_1"].geometry}
        material={materials.colormap}
      >
        <mesh
          name="arm"
          geometry={nodes.arm.geometry}
          material={materials.colormap}
          position={[0, 1.459, 0]}
        >
          <mesh
            name="catapult_2"
            geometry={nodes.catapult_2.geometry}
            material={materials.colormap}
            position={[-0.994, -0.003, 0]}
          />
          <mesh
            name="weight_2"
            geometry={nodes.weight_2.geometry}
            material={materials.colormap}
            position={[0.572, 0.017, 0]}
          />
        </mesh>
        <mesh
          name="catapult"
          geometry={nodes.catapult.geometry}
          material={materials.colormap}
          position={[-0.994, 1.456, 0]}
        />
        <mesh
          name="weight"
          geometry={nodes.weight.geometry}
          material={materials.colormap}
          position={[0.572, 1.476, 0]}
        />
        <mesh
          name="wheel"
          geometry={nodes.wheel.geometry}
          material={materials.colormap}
          position={[0.472, 0.201, -0.538]}
        />
        <mesh
          name="wheel_1"
          geometry={nodes.wheel_1.geometry}
          material={materials.colormap}
          position={[-0.472, 0.201, -0.538]}
        />
        <mesh
          name="wheel_2"
          geometry={nodes.wheel_2.geometry}
          material={materials.colormap}
          position={[-0.472, 0.201, 0.538]}
        />
        <mesh
          name="wheel_3"
          geometry={nodes.wheel_3.geometry}
          material={materials.colormap}
          position={[0.472, 0.201, 0.538]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/public/castle/GLB_format/siege-trebuchet.glb");
