/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../../public/castle/GLB_format/siege-ballista.glb -t -k 
*/

import * as THREE from "three";
import { type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["siege-ballista_1"]: THREE.Mesh;
    arrow: THREE.Mesh;
    wheel: THREE.Mesh;
    wheel_1: THREE.Mesh;
  };
  materials: {
    colormap: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/public/castle/GLB_format/siege-ballista.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="siege-ballista_1"
        geometry={nodes["siege-ballista_1"].geometry}
        material={materials.colormap}
      >
        <mesh
          name="arrow"
          geometry={nodes.arrow.geometry}
          material={materials.colormap}
          position={[0.326, 0.416, 0]}
        />
        <mesh
          name="wheel"
          geometry={nodes.wheel.geometry}
          material={materials.colormap}
          position={[0.438, 0.201, -0.434]}
        />
        <mesh
          name="wheel_1"
          geometry={nodes.wheel_1.geometry}
          material={materials.colormap}
          position={[0.438, 0.201, 0.434]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/public/castle/GLB_format/siege-ballista.glb");
