/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../public/castle/GLB_format/tower-base.glb -t -k 
*/

import * as THREE from "three";
import { type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
type GLTFResult = GLTF & {
  nodes: {
    ["tower-base_1"]: THREE.Mesh;
  };
  materials: {
    colormap: THREE.MeshStandardMaterial;
  };
};

export function TowerBase(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/public/castle/GLB_format/tower-base.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="tower-base_1"
        geometry={nodes["tower-base_1"].geometry}
        material={materials.colormap}
      />
      {props.children}
    </group>
  );
}

useGLTF.preload("/public/castle/GLB_format/tower-base.glb");
