/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 wall-narrow.glb -t -k 
*/

import * as THREE from 'three'
import { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['wall-narrow_1']: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
}

export function WallNarrow(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/public/castle/GLB_format/wall-narrow.glb'
  ) as unknown as GLTFResult

  return (
    <group {...props} dispose={null}>
      <mesh
        name="wall-narrow_1"
        geometry={nodes['wall-narrow_1'].geometry}
        material={materials.colormap}
      />
    </group>
  )
}

useGLTF.preload('/public/castle/GLB_format/wall-narrow.glb')
